#include"Declarations.h"
int main()
{
	Employee E1;
	cout<<"-------------------------------------------------------------------------"<<endl;
	cout<<"                    :DISPLAY USING DEFAULT CONSTRUCTOR:                  "<<endl;
    cout<<"-------------------------------------------------------------------------"<<endl;
    cout<<"Name:"<<E1.get_Emp_name()<<endl;
    cout<<"Salary:"<<E1.get_Emp_salary()<<endl;
    cout<<"Num:"<<E1.get_Emp_num()<<endl;
    cout<<"Designation:"<<E1.get_Emp_designation()<<endl;
    cout<<endl;
    cout<<"----------------------------------------"<<endl;
    cout<<"Number of Employee Objects now:"<<Employee::get_no_of_obj()<<endl;
    cout<<"----------------------------------------"<<endl<<endl;;
    cout<<endl;
	Employee E2(23);
    E2.Set_Emp_name("Amna Muzaffar");
	E2.Set_Emp_salary(15000);
	E2.Set_Emp_designation("Professor");
	cout<<"-------------------------------------------------------------------------"<<endl;
	cout<<"    :DISPLAY USING PARAMETERIZED CONSTRUCTOR AND GEETERS AND SETTERS:    "<<endl;
	cout<<"-------------------------------------------------------------------------"<<endl;
	cout<<"Details of 1st Employee:"<<endl;
	cout<<"Employee Name:"<<E2.get_Emp_name()<<endl;
	cout<<"Employee Number:"<<E2.get_Emp_num()<<endl;
	cout<<"Employee salary:"<<E2.get_Emp_salary()<<endl;
	cout<<"Employee Designation:"<<E2.get_Emp_designation()<<endl;
	cout<<endl<<endl;
	cout<<"----------------------------------------"<<endl;
    cout<<"Number of Employee Objects now:"<<Employee::get_no_of_obj()<<endl;
    cout<<"----------------------------------------"<<endl<<endl;
	Employee E3(E2);
	cout<<"-------------------------------------------------------------------------"<<endl;
	cout<<"              :COPY CONSTRUCTOR TO DEAL WITH SHALLOW COPY:               "<<endl;
	cout<<"-------------------------------------------------------------------------"<<endl;
    cout<<"Employee Name:"<<E3.get_Emp_name()<<endl;
	cout<<"Employee Number:"<<E3.get_Emp_num()<<endl;
	cout<<"Employee salary:"<<E3.get_Emp_salary()<<endl;
	cout<<"Employee Designation:"<<E3.get_Emp_designation()<<endl;
	cout<<endl;
	cout<<"----------------------------------------"<<endl;
    cout<<"Number of Employee Objects now:"<<Employee::get_no_of_obj()<<endl;
    cout<<"----------------------------------------"<<endl<<endl;
    cout<<"-------------------------------------------------------------------------"<<endl;
	cout<<"                        :DEMONSTRATION OF CASCADING:                     "<<endl;
	cout<<"-------------------------------------------------------------------------"<<endl;
    Employee E4(23);
	E4.Set_Emp_name("Sana").Set_Emp_salary(14000);
   E4.Set_Emp_designation("Teacher");
    cout<<"Employee Name:"<<E4.get_Emp_name()<<endl;
    cout<<"Employee Salary:"<<E4.get_Emp_salary()<<endl;
    cout<<"Employee Number:"<<E4.get_Emp_num()<<endl;
    cout<<"Employee Designation:"<<E4.get_Emp_designation()<<endl;
    cout<<endl;
    cout<<"----------------------------------------"<<endl;
    cout<<"Number of Employee Objects now:"<<Employee::get_no_of_obj()<<endl;
    cout<<"----------------------------------------"<<endl<<endl;
    cout<<"-------------------------------------------------------------------------"<<endl;
    cout<<"                        Total Employee Objects are:"<<Employee::get_no_of_obj()<<"                    "<<endl;
    cout<<"-------------------------------------------------------------------------"<<endl;
    cout<<endl<<endl;
    cout<<"-------------------------------------------------------------------------"<<endl;
    cout<< "                              :DESTRUCTORS:                              "<<endl;
    cout<<"-------------------------------------------------------------------------"<<endl;
}
